export const FETCH_ROWS_REQUEST = 'RT.FETCH_ROWS_REQUEST';
export const FETCH_ROWS_FAILURE = 'RT.FETCH_ROWS_FAILURE';
export const FETCH_ROWS_SUCCESS = 'RT.FETCH_ROWS_SUCCESS';
export const CHANGE_MAXIMUM_ROWS = 'RT.CHANGE_MAXIMUM_ROWS';

export const SORTBY = 'RT.SORTBY';
export const TOGGLE_SORT_DIRECTION = 'RT.TOGGLE_SORT_DIRECTION';
export const FILTER_BY_USERNAME = 'RT.FILTER_BY_USERNAME';
export const RESET_USERNAME_SEARCH_FILTER = 'RT.RESET_USERNAME_SEARCH_FILTER';

export const UPDATE_CURRENT_PAGINATION_PAGE = 'RT.UPDATE_CURRENT_PAGINATION_PAGE';
export const ADD_NEW_ROW = 'RT.ADD_NEW_ROW';
